# Generated by Django 2.2 on 2019-04-08 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allotment',
            old_name='budget_period_id',
            new_name='budget_period',
        ),
        migrations.RenameField(
            model_name='budgetperiod',
            old_name='budget_id',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='budget_period_id',
            new_name='budget_period',
        ),
        migrations.RenameField(
            model_name='expensespent',
            old_name='period_expense_id',
            new_name='period_expense',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='budget_period_id',
            new_name='budget_period',
        ),
        migrations.RenameField(
            model_name='periodexpense',
            old_name='budget_period_id',
            new_name='budget_period',
        ),
    ]
