# Generated by Django 2.2 on 2019-04-14 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_category_default_allotment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodExpenseAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_allotment', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='periodexpense',
            name='name',
        ),
        migrations.AddField(
            model_name='periodexpense',
            name='period_expense_allotment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.PeriodExpenseAllotment'),
        ),
    ]
