# Generated by Django 2.2 on 2019-04-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20190413_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodexpense',
            name='is_long_term',
        ),
        migrations.AddField(
            model_name='periodexpenseallotment',
            name='is_long_term',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
