# Generated by Django 2.2 on 2019-05-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20190413_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetPeriod')),
            ],
        ),
    ]
